name: Strip widget metadata

permissions:
  contents: write

on:
  push:
    paths:
      - '**/*.ipynb'
      - '.github/workflows/strip-widgets.yml'

jobs:
  strip_widgets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout completo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Instalar jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Limpiar metadata.widgets
      run: |
        find . -name '*.ipynb' -print0 \
        | xargs -0 -n1 -I{} sh -c \
            "jq 'del(.metadata.widgets) | .cells |= map(del(.metadata.widgets))' '{}' > /tmp/nb && mv /tmp/nb '{}'"

    - name: Commit y push si hay cambios
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add '**/*.ipynb'
        if ! git diff --cached --quiet; then
          git commit -m "chore: strip metadata.widgets"
          git push
        else
          echo "🟢 No hay widgets que limpiar."
        fi
